# requirements.yaml
dependencies:
- name: prometheus
  version: 11.12.0
  repository: https://charts.helm.sh/stable
  alias: prometheus
- name: grafana
  version: 5.5.5
  repository: https://charts.helm.sh/stable
  alias: grafana
