{{- if index .Values "image-watcher" "ingress" "enabled" -}}
apiVersion: {{ template "apiVersion.Ingress" . }}
kind: Ingress
metadata:
  name: {{ include "ml-operator.name" . }}-ingress
  labels:
    {{- include "ml-operator.labels" . | nindent 4 }}
{{- with index .Values "image-watcher" "ingress" "annotations" }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    # Host based ingress
    - host: {{index .Values "image-watcher" "ingress" "host"}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: image-watcher
                port: 
                  number: {{ index .Values "image-watcher" "ingress" "port" }}

    # Path based ingress
    - http:
        paths:
          - path: {{ index .Values "image-watcher" "ingress" "path" }}
            pathType: Prefix
            backend:
              service:
                name: image-watcher
                port:
                  number: {{ index .Values "image-watcher" "ingress" "port" }}
{{- end }}