# requirements.yaml
dependencies:
- name: bulk-api-adapter
  version: 11.1.0
  repository: "file://../bulk-api-adapter"
  condition: bulk-api-adapter.enabled
- name: bulk-centralledger
  version: 12.3.1
  repository: "file://../bulk-centralledger"
  condition: bulk-centralledger.enabled
- name: mongodb
  version:  7.8.10
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  alias: mongodb
  condition: mongodb.enabled
