# requirements.yaml
dependencies:
- name: centralkms
  version: 2.4.0
  repository: "file://../centralkms"
  condition: centralkms.enabled
- name: postgresql
  version: 0.9.1
  repository: https://charts.helm.sh/stable
  condition: postgresql.enabled
