# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
apiVersion: v1
items:
- apiVersion: v1
  data:
    .dockerconfigjson: >-
    
      eyJhdXRocyI6eyJtb2phbG9vcGhlbG0uYXp1cmVjci5pbyI6eyJ1c2VybmFtZSI6Im1vamFsb29waGVsbSIsInBhc3N3b3JkIjoiMFdHRXVURHROTHZHSnczblMxRWtkL3c9K3RSMVNhVGUiLCJlbWFpbCI6Im1haWxhZGR5IiwiYXV0aCI6ImJXOXFZV3h2YjNCb1pXeHRPakJYUjBWMVZFUjBUa3gyUjBwM00yNVRNVVZyWkM5M1BTdDBVakZUWVZSbCJ9fX0=
  kind: Secret
  metadata:
    name: pullsecret
    namespace: {{namespace}}
  type: kubernetes.io/dockerconfigjson
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: dfspid
    namespace: {{namespace}}
    labels:
      k8s-app: dfspid
  spec:
    replicas: 1
    selector:
      matchLabels:
        k8s-app: dfspid
    template:
      metadata:
        name: dfspid
        labels:
          k8s-app: dfspid
      spec:
        containers:
          - name: dfspid
            image: {devops}/dfspid:develop
            env:
            - name: SWAGGER_PREFIX
              value: "/dfspid/"
            - name: SWAGGERFILE_PREFIX
              value: "/dfspid/"
            - name: MYSQL_PASSWORD
              value: "oyMxgZChuu"
            - name: MYSQL_USER
              value: "central_ledger"
            - name: MYSQL_DATABASE
              value: "central_ledger"
            - name: MYSQL_SERVER
              value: "{{sqlendpoint}}"
            - name: MYSQL_PORT
              value: '3306'
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: Always
            securityContext:
              privileged: false
              procMount: Default
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        imagePullSecrets:
          - name: pullsecret
        schedulerName: default-scheduler
    revisionHistoryLimit: 10
    progressDeadlineSeconds: 600
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: servicerewrites
    namespace: {{namespace}}
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      nginx.ingress.kubernetes.io/cors-allow-headers: X-Forwarded-For
      nginx.ingress.kubernetes.io/proxy-body-size: 500m
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/use-regex: 'true'
  spec:
    rules:
      - host: {{urlforcluster}}
        http:
          paths:
            - path: /dfspid(/|$)(.*)
              pathType: ImplementationSpecific
              backend:
                service:
                  name: dfspid
                  port:
                    number: 8080
- apiVersion: v1
  kind: Service
  metadata:
    name: dfspid
    namespace: {{namespace}}
    labels:
      k8s-app: dfspid
  spec:
    ports:
      - name: tcp-8080
        protocol: TCP
        port: 8080
        targetPort: 8080
    selector:
      k8s-app: dfspid
    type: ClusterIP
    sessionAffinity: None
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""